### PR TITLE
Seeder created successful.

### PR DESCRIPTION
**Pull request by Ayush8923**
Issue #125

### CODE REVIEW

**Review by balendurawat — CHANGES_REQUESTED** [review]
jmc

**Comment by balendurawat** [comment]
first think then write

**Comment by balenduR** [comment]
You have seeded in the columns which are not present but you have not seeded in the columns which are present.

**Comment by Ayush8923** [comment]
I don't understand what you are saying 
And which file are you talking about in which column has not been created but that column is there in the database?
Please comment that file by mentioning it.

**Comment by Ayush8923** [comment]
And stop writing this jmc-jmc word.

**Comment by Devyush** [comment]
jmc

**Pull request closed without merging**
